# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='projects',
            name='content',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='design',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='projects',
            name='usability',
            field=models.IntegerField(default=0),
        ),
    ]
