# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-25 09:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0003_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='content',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rates',
            name='design',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='rates',
            name='project',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rates',
            name='usability',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
