# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-26 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0005_auto_20190525_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-profile']},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-name']},
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(max_length=60),
        ),
    ]
